#### Name = Pranjal Keshav Patil
#### Roll No = 45

In [1]:
import numpy as np

##### 1. Array Creation Techniques

In [2]:
print("1. Array Creation Techniques")

1. Array Creation Techniques


##### a. Creating an array from a list

In [3]:
array_from_list = np.array([1, 2, 3, 4, 5])
array_from_list

array([1, 2, 3, 4, 5])

##### b. Using arange()


In [4]:
array_arange = np.arange(0, 10, 2)
array_arange

array([0, 2, 4, 6, 8])

##### c. Using linspace()

In [5]:
array_linspace = np.linspace(0, 10, 5)  # Divides 0 to 10 into 5 points
array_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

##### d. Using zeros()


In [6]:
array_zeros = np.zeros((3, 3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

##### e. Using ones()

In [7]:
array_ones = np.ones((2, 2))
array_ones

array([[1., 1.],
       [1., 1.]])

##### f. Using eye() for identity matrix


In [8]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##### g. Using random() for random values

In [9]:
array_random = np.random.random((3, 3))
array_random

array([[0.78855821, 0.8249925 , 0.89708205],
       [0.49902233, 0.52159067, 0.05378163],
       [0.49314013, 0.60488843, 0.78315216]])

##### 2. Different NumPy Methods

In [10]:
print("\n2. NumPy Methods")


2. NumPy Methods


##### a. Reshaping an array

In [11]:
reshaped_array = np.arange(1, 10).reshape(3, 3)
reshaped_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##### b. Transposing an array

In [12]:
transposed_array = reshaped_array.T
transposed_array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

##### c. Mathematical operations

In [13]:
array_math = np.array([1, 2, 3])
array_math + 2
array_math * 3
np.sqrt(array_math)

array([1.        , 1.41421356, 1.73205081])

#####  d. Aggregation methods

In [14]:
np.sum(array_math)
np.mean(array_math)
np.max(array_math)
np.min(array_math)

np.int32(1)

##### e. Concatenation of arrays

In [15]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concat_array = np.concatenate((array_a, array_b))
concat_array

array([1, 2, 3, 4, 5, 6])

##### f. Sorting an array